# Generated by Django 4.1 on 2025-08-19 12:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('live_url', models.URLField(blank=True)),
                ('git_url', models.URLField(blank=True)),
                ('date_created', models.DateField()),
                ('frameworks_used', models.ManyToManyField(limit_choices_to={'category': 'framework'}, related_name='projects_frameworks', to='my_projects.technology')),
                ('languages_used', models.ManyToManyField(limit_choices_to={'category': 'language'}, related_name='projects_languages', to='my_projects.technology')),
            ],
        ),
    ]
