# Generated by Django 4.1 on 2025-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frameworks_used',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'framework'}, related_name='projects_frameworks', to='my_projects.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages_used',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'language'}, related_name='projects_languages', to='my_projects.technology'),
        ),
    ]
